# Generated by Django 5.1.3 on 2025-01-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_orderedby_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_amount',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
