# Generated by Django 5.1.3 on 2025-01-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_product_stock_amount_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
