# Generated by Django 5.1.3 on 2025-01-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordered',
            name='size',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
