# Generated by Django 5.1.3 on 2025-01-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ordered_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
