# Generated by Django 5.1.3 on 2025-01-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='added_date',
        ),
    ]
